worker_processes auto;
rtmp_auto_push on;
error_log /dev/stdout info;

events {
    worker_connections 1024;
}

rtmp {
    # This line enables logs to Docker stdout
    access_log /dev/stdout;
    server {
        listen 1935; # Standard RTMP port
        chunk_size 4096;

        application live {
            live on;
            record off;

            # Optional: Enable HLS for browser playback
            hls on;
            hls_path /tmp/hls;
            hls_fragment 3s;
            hls_playlist_length 12s;
            hls_cleanup on;
        }
    }
}

http {
    access_log /dev/stdout;
    error_log /dev/stdout info;

    server {
        listen 8080;    # Port for HLS playback
        location /hls {
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            root /tmp;
            add_header Cache-Control no-cache;
        }
    }
}